{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "opensearch.uname" . }}-config
  labels:
    app: "{{ template "opensearch.uname" . }}"
    {{- include "opensearch.labels" . | indent 4 }}
data:
{{- range $configName, $configYaml := .Values.config }}
  {{ $configName }}: |
    {{- toYaml $configYaml | nindent 4 }}
{{- end -}}
{{- end -}}
