---
{{- if .Values.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "opensearch.uname" . }}-pdb"
  labels:
    {{- include "opensearch.labels" . | indent 4 }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{ template "opensearch.uname" . }}"
{{- end }}
